### ISSUE TITLE
Font size in various resolutions

### ISSUE THREAD

**Issue by kgarlicki** [bkiziuk/service.subsmangler#14]
Hi there, thanks for your work on this addon. It's very useful for getting really _grey_ subtitles for HDR content (because white burns in into your eyes) but I've got an issue with font size between 1080p and 4k videos. When I set font size to 16 it's perfect for 4K, but in 1080p 16 turns out as too big. Is there any way to make it consistent between different resolutions?

**Comment by bkiziuk** [comment]
Hi. This would be troublesome to handle different resolutions by adjusting font size during conversion, but let me check how Kodi handles it.

**Comment by mkaflowski** [comment]
I think there is a problem with different aspect ratios. 16:9 has bigger subtitles.

**Comment by bkiziuk** [comment]
Looks like it is not addon's issue per se as it relies on Kodi subtitle subsystem for displaying subtitles.
