### ISSUE TITLE
3D subtitles

### ISSUE THREAD

**Issue by Pl1997** [bkiziuk/service.subsmangler#15]
Hello,

Thank you very much for this add-on ! Could it be used to convert standard subtitles to 3D side by side subtitles ? Perhaps using this ? https://gist.github.com/ArmyOfPirates/f06e307daaa3abc48ef3#file-srt2sbs3d-py

Thanks for your answer !

**Comment by Pl1997** [comment]
Woops, a little more forum browsing made me feel like I might have missed a native feature of Kodi... I will check that and close the issue if such a function has already been implemented

**Comment by bkiziuk** [comment]
Currently not in plan.
