### ISSUE TITLE
Version 2.0 for Matrix

### ISSUE THREAD

**Issue by sasagr** [bkiziuk/service.subsmangler#17]
Is it available? Don’t see it in the repo or here as released.

**Comment by bkiziuk** [comment]
Hi, not yet. Actually you can download the current source and install it manually in Kodi tree. It should work, but I was planning to do some more testing before releasing it. I also want to update embedded pysubs2 library.

**Comment by sasagr** [comment]
Done it! It seems to work fine, no errors. Thanks! I guess I will get now official updates once v > 2.0.0
