### ISSUE TITLE
Ads not removed

### ISSUE THREAD

**Issue by sasagr** [bkiziuk/service.subsmangler#20]
I m using the current latest version 2.0.0 for Matrix from master branch.
For some reason the ads are not removed. Pls see screenshot.
I also tried to edit the regexdef.def file adding:
.*OpenSubtitles.*
.*Support us.*
but no luck.
https://imgur.com/a/3Ih945V

Here the smangler.log with debug
https://pastebin.com/SknMfGVS

**Comment by bkiziuk** [comment]
What is the source of those subtitles? Are they provided from the video plugin or they are opened locally?

**Comment by sasagr** [comment]
I disabled the plugin subs and open/downloaded the sub my self calling the sub dialog.
By the way... I tried to change the setting to invoke always the download dialog from your settings but it does not make a difference

**Comment by bkiziuk** [comment]
It turns out that the plugin does not work very well with streaming services. The original idea was to mainly support local content. I need to look into it a bit more.

**Comment by bkiziuk** [comment]
There were some crashes that caused the plugin to stop work. It could also be a reason for not processing the file. 
 86250298e03aabbd6ed9279e57ed5fad3c4d7333
