### ISSUE TITLE
Subtitle Mangler fails with Kodi 20

### ISSUE THREAD

**Issue by Zuikkis** [bkiziuk/service.subsmangler#34]
Kodi 20 Nexus seems to have more advanced subtitle color settings. This causes Subtitle Mangler to fail on startup:

```

                Error Type: <class 'ValueError'>
          Traceback (most recent call last):
            File "/storage/emulated/0/Kodi/files//.kodi/addons/service.subsmangler/service.py", line 8, in <module>
              smangler.PreparePlugin()
            File "/storage/emulated/0/Kodi/files//.kodi/addons/service.subsmangler/resources/lib/smangler.py", line 157, in PreparePlugin
              GetKodiSubtitleSettings()
            File "/storage/emulated/0/Kodi/files//.kodi/addons/service.subsmangler/resources/lib/smangler.py", line 466, in GetKodiSubtitleSettings
              globals.__addon__.setSetting("FontSize", str(GetKodiSetting('subtitles.height')))
            File "/storage/emulated/0/Kodi/files//.kodi/addons/service.subsmangler/resources/lib/smangler.py", line 501, in GetKodiSetting
              raise ValueError
          ValueError

```

I don't know, maybe you could just remove the subtitle appearance settings completely, I prefer to adjust them in Kodi settings anyway?

**Comment by bkiziuk** [comment]
Let me look into this. 
The basic issue is that Kodi 20 is at an early stage of development, so there's a high chance that there are going to be more things that will need to be adjusted in the future. On the other hand I don't want to keep patching the code back and forth for every nightly-build, so I rather prefer to wait for at least Beta release.

**Comment by Zuikkis** [comment]
Yes, I understand.

I switched to 20 in hopes that it would fix some video playback issues I was having. So far it's looking good with no big issues, except for this thing with Subtitle Mangler. :)

For what it's worth, "AutoSub" plugin doesn't work either, but I would prefer Subtitle Mangler anyway. :)

**Comment by unacceptablex** [comment]
now that the kodi nexus is in beta stage can you please update this useful add-on for kodi nexus?

many thanks

**Comment by bkiziuk** [comment]
Working on it. You can temporarily pull the Nexus branch to see if it works.
At the moment I have some issues with my NFS storage so I'm finding it difficult to properly test it.

**Comment by bkiziuk** [comment]
Ok. Changes submitted to Kodi repo.
